// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-fDKs-3i9IWR3bgrByVCTTH5Qcqk7VU0',
    appId: '1:46516879621:web:3cc6dd5491ec32f125776c',
    messagingSenderId: '46516879621',
    projectId: 'chat-app-b900e',
    authDomain: 'chat-app-b900e.firebaseapp.com',
    storageBucket: 'chat-app-b900e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbxeUCp9Ze-hIWgctMLixmahTK8SClC4g',
    appId: '1:46516879621:android:35e2082c54c211f625776c',
    messagingSenderId: '46516879621',
    projectId: 'chat-app-b900e',
    storageBucket: 'chat-app-b900e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrD-76bI8fQbaCE-mMqjs5m6KxyEn5Dqs',
    appId: '1:46516879621:ios:dfcc574ae8c68fcd25776c',
    messagingSenderId: '46516879621',
    projectId: 'chat-app-b900e',
    storageBucket: 'chat-app-b900e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrD-76bI8fQbaCE-mMqjs5m6KxyEn5Dqs',
    appId: '1:46516879621:ios:dfcc574ae8c68fcd25776c',
    messagingSenderId: '46516879621',
    projectId: 'chat-app-b900e',
    storageBucket: 'chat-app-b900e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-fDKs-3i9IWR3bgrByVCTTH5Qcqk7VU0',
    appId: '1:46516879621:web:45da2da9ffa4924d25776c',
    messagingSenderId: '46516879621',
    projectId: 'chat-app-b900e',
    authDomain: 'chat-app-b900e.firebaseapp.com',
    storageBucket: 'chat-app-b900e.appspot.com',
  );
}
